name: mealknight
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  adaptive_theme: 3.6.0
  animated_bottom_navigation_bar: ^1.3.3
  animations: ^2.0.11
  awesome_notifications: 0.9.3+1
  banner_carousel: ^1.2.1 #2 years
  basic_utils: ^5.7.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  chewie: ^1.8.1
  cloud_firestore: ^5.1.0
  contained_tab_bar_view: ^0.8.0 #2 years , used in main_search.page.dar , and no usage, clarify
  cool_alert: ^2.0.1
  country_picker: 2.0.26
  crypto: ^3.0.3
  currency_formatter: ^2.2.1
  custom_clippers: ^2.0.0 #2 years
  custom_faqs:
    git:
      url: https://github.com/ambrosethebuild/custom_faqs
      ref: main
  custom_sliding_segmented_control: 1.8.3
  dartx: ^1.2.0
  dio: ^5.5.0+1
  dotted_border: ^2.1.0
  dotted_line: ^3.2.2
  dynamic_height_grid_view: ^0.0.4
  expand_widget: ^3.1.1
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_crashlytics: ^4.0.3
  firebase_dynamic_links: ^6.0.3
  firebase_messaging: ^15.0.3
  firestore_chat: ^0.1.2
  dash_chat_2: ^0.0.21
  fl_location: ^3.1.0
  flag: ^7.0.0
  flutter_facebook_auth: ^7.0.1
  flutter_form_builder: ^9.3.0
  flutter_icons:
    git:
      url: https://github.com/imclerran/flutter-icons.git
      ref: dart-3
  flutter_image_compress: ^2.3.0
  flutter_inappwebview: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_overboard: ^3.1.3
  flutter_polyline_points: ^2.1.0
  flutter_rating_bar: ^4.0.1 #2 years
  flutter_signin_button: ^2.0.0 #3 years , only design is there, can be removed
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  fluttercontactpicker: ^5.0.0
  fluttertoast: ^8.2.6
  geolocator: ^12.0.0
  glass: ^2.0.0+1
  glass_kit: 4.0.1
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  google_maps_place_picker_mb: ^3.1.2
  google_places_flutter: ^2.0.8
  google_sign_in: ^6.2.1
  group_radio_button: 1.3.0
  html_unescape: ^2.0.0
  http: ^1.2.1
  image_picker: 1.1.2
  in_app_review: ^2.0.9
  intl: ^0.19.0
  inspection: ^0.0.13 #2 years , laravel like validator can be replaced
  jiffy: ^6.3.1
  keyboard_dismisser: ^3.0.0 #2 years
  line_icons: ^2.0.3
  localize_and_translate: ^5.1.2
  location: ^7.0.0
  map_launcher: ^3.3.1
  maps_toolkit: ^3.0.0
  masonry_grid: ^1.0.0 #2 years
  measure_size: ^4.0.0
  package_info_plus: ^8.0.0
  pin_code_fields: ^8.0.1
  pinch_zoom: ^2.0.0
  pretty_dio_logger: ^1.3.1
  pull_to_refresh_flutter3: ^2.0.2
  mobile_scanner: ^5.1.0
  qr_flutter: ^4.1.0
  rx_shared_preferences: ^3.1.0
  rxdart: ^0.27.7
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  sign_in_with_apple: ^6.1.1
  slide_countdown: ^1.6.1
  sliding_up_panel: ^2.0.0+1 #2 years , used only in taxi module
  smooth_page_indicator: ^1.2.0
  spider: ^4.2.2
  square_in_app_payments: ^1.7.9
  stacked: 3.4.3
  stacked_services: ^1.5.0
  stacked_shared: ^1.4.1
  stacked_themes: ^0.3.13
  synchronized: ^3.1.0+1
  timelines: ^0.1.0 #3 years
  upgrader: ^10.2.0
  url_launcher: ^6.3.0
  velocity_x: ^4.2.1
  otp_text_field: ^1.1.3 #2 years
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  dropdown_button2: 2.3.9
  geocoding: 3.0.0

dependency_overrides:
  intl: ^0.19.0
  package_info_plus: ^4.1.0
  geolocator: ^12.0.0
  js: ^0.6.4
  firebase_core: ^3.2.0
  cloud_firestore: ^5.1.0

dev_dependencies:
  flutter_application_id: ^2.0.0-dev  #3 years
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  translator: ^1.0.0
  build_runner: ^2.4.11
  stacked_generator: ^1.6.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/mealknight.jpg"
  adaptive_icon_foreground: "assets/icons/mealknight.jpg"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/mealknight.jpg"
    background_color: "#ffffff"
    theme_color: "#0000FF"
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/icons/
    - assets/images/svg/
    - assets/json/
    - assets/lang/
    - assets/

  fonts:
    - family: ComicSans
      fonts:
        - asset: assets/fonts/comicSansFonts/COMIC.TTF